# Generated by Django 3.0.5 on 2020-11-23 19:46

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('Team_5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', to='Team_5.Listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(blank=True, storage=djongo.storage.GridFSStorage(base_url='C:\\Users\\Do-While\\Desktop\\Local branch 202\\fa20-cmpe-202-sec-03-team-project-team-5\\djangoBackendmyfiles/', collection='myfiles'), upload_to='userphoto'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(blank=True, storage=djongo.storage.GridFSStorage(base_url='C:\\Users\\Do-While\\Desktop\\Local branch 202\\fa20-cmpe-202-sec-03-team-project-team-5\\djangoBackendmyfiles/', collection='myfiles'), upload_to='userphoto'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(blank=True, storage=djongo.storage.GridFSStorage(base_url='C:\\Users\\Do-While\\Desktop\\Local branch 202\\fa20-cmpe-202-sec-03-team-project-team-5\\djangoBackendmyfiles/', collection='myfiles'), upload_to='userphoto'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_4',
            field=models.ImageField(blank=True, storage=djongo.storage.GridFSStorage(base_url='C:\\Users\\Do-While\\Desktop\\Local branch 202\\fa20-cmpe-202-sec-03-team-project-team-5\\djangoBackendmyfiles/', collection='myfiles'), upload_to='userphoto'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_5',
            field=models.ImageField(blank=True, storage=djongo.storage.GridFSStorage(base_url='C:\\Users\\Do-While\\Desktop\\Local branch 202\\fa20-cmpe-202-sec-03-team-project-team-5\\djangoBackendmyfiles/', collection='myfiles'), upload_to='userphoto'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_6',
            field=models.ImageField(blank=True, storage=djongo.storage.GridFSStorage(base_url='C:\\Users\\Do-While\\Desktop\\Local branch 202\\fa20-cmpe-202-sec-03-team-project-team-5\\djangoBackendmyfiles/', collection='myfiles'), upload_to='userphoto'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(blank=True, storage=djongo.storage.GridFSStorage(base_url='C:\\Users\\Do-While\\Desktop\\Local branch 202\\fa20-cmpe-202-sec-03-team-project-team-5\\djangoBackendmyfiles/', collection='myfiles'), upload_to='userphoto'),
        ),
    ]
