# Generated by Django 3.0.5 on 2020-11-23 19:59

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('Team_5', '0002_auto_20201123_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(blank=True, storage=djongo.storage.GridFSStorage(base_url='djangoBackend.urlsmyfiles/', collection='myfiles'), upload_to='userphoto'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(blank=True, storage=djongo.storage.GridFSStorage(base_url='djangoBackend.urlsmyfiles/', collection='myfiles'), upload_to='userphoto'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(blank=True, storage=djongo.storage.GridFSStorage(base_url='djangoBackend.urlsmyfiles/', collection='myfiles'), upload_to='userphoto'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_4',
            field=models.ImageField(blank=True, storage=djongo.storage.GridFSStorage(base_url='djangoBackend.urlsmyfiles/', collection='myfiles'), upload_to='userphoto'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_5',
            field=models.ImageField(blank=True, storage=djongo.storage.GridFSStorage(base_url='djangoBackend.urlsmyfiles/', collection='myfiles'), upload_to='userphoto'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_6',
            field=models.ImageField(blank=True, storage=djongo.storage.GridFSStorage(base_url='djangoBackend.urlsmyfiles/', collection='myfiles'), upload_to='userphoto'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(blank=True, storage=djongo.storage.GridFSStorage(base_url='djangoBackend.urlsmyfiles/', collection='myfiles'), upload_to='userphoto'),
        ),
    ]
