# Generated by Django 3.0.5 on 2020-11-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team_5', '0006_auto_20201124_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='C:\\Users\\Do-While\\Desktop\\Local branch 202\\fa20-cmpe-202-sec-03-team-project-team-5\\djangoBackend\\media/images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='C:\\Users\\Do-While\\Desktop\\Local branch 202\\fa20-cmpe-202-sec-03-team-project-team-5\\djangoBackend\\media/images/'),
        ),
    ]
